### ISSUE TITLE
Exceptions in BaseKernel.complete implementations are ignored

### ISSUE THREAD

**Issue by dgelessus** [SpencerPark/jupyter-jvm-basekernel#10]
When an implementation of `BaseKernel.complete` throws an exception, it seems to be ignored. Although `BaseKernel.handleCompleteRequest` calls `replyError` when an exception happens, that doesn't appear to do anything - the error is not reported in the Jupyter web interface or on the console.

I don't know if this is an issue in the basekernel (i. e. the error not being passed on correctly) or in Jupyter (i. e. the error being received but not shown/logged). Maybe the basekernel should log the caught exception just to be sure.

**Comment by SpencerPark** [comment]
Sorry for the late reply on this. From what I can tell the base kernel is properly following the protocol in this scenario. [completion_request](https://jupyter-client.readthedocs.io/en/5.2.3/messaging.html#completion) says 

```python
# status should be 'ok' unless an exception was raised during the request,
# in which case it should be 'error', along with the usual error message content
# in other messages.
'status' : 'ok'
```

I believe it is the front-end not properly doing something with the exception as the notebook (web page) does receive the error so the jupyter_client is sending it but then the notebook does nothing with it. I was reading the notebook code and it the only place it was used (to populate the tool tip) returned early if the reply didn't contain the `found` field set to true. The same behavior is present in jupyter lab and it looks like nteract as well. 

The problem seems to be upstream. I would like to try and keep the semantics of the kernel handlers as close to the semantics of the message they wrap and as such the `error` reply is an acceptable (and non-erroneous) way to handle the reply. We wouldn't log errors in `eval` and the semantics of `complete` errors are _supposed to be_ the same so they shouldn't be treated differently. Of course you are free to implement it how you wish but the keep with the protocol I don't want to do anything special (no matter how minor) with the error.
