### ISSUE TITLE
Allow disabling automatic redirection of System.out/err during eval calls

### ISSUE THREAD

**Issue by dgelessus** [SpencerPark/jupyter-jvm-basekernel#7]
Hi, first of all thank you for this base kernel, it's been very useful for me so far 😃

Currently the base kernel automatically redirects Java's `System.out` and `System.err` to Jupyter during `eval` calls. While this is useful for something like IJava, where the user code will likely use `System.out` directly, my use case is a little different: I'm writing a kernel for a language which has a Java API, but doesn't run on the JVM itself, so `System.out` is never used by the user code.

That alone wouldn't be an issue, but in my case `System.out` is also being used for logging, so at the moment all log messages during `eval` are sent to Jupyter instead of the console. (I could redirect my own log messages to a file, but that is less convenient to read, and I also have some dependencies that unconditionally log to `System.out`.) In this case it would be useful if a kernel could disable the automatic redirection, and instead use separate streams that go to Jupyter (something like `this.getStdout().println(...)`). That way a kernel could send output to both `System.out` and Jupyter at the same time.

**Comment by SpencerPark** [comment]
Hi @dgelessus, really excited to hear you are getting use out of the project! 

You bring up a point I was contemplating for some time before deciding on always replacing the streams. The reason being that if access to actual stdout/err/in streams they can be taken and saved in the constructor but for the most part anything printed belongs to the user (which is located at the front-end). Additionally the logic for redirecting the streams was not trivial enough to leave it to concrete kernel implementations.

I think that your suggestion of opting out of this automatic redirection is a good compromise though. I recently needed to expose a `display` method so that user code could write to the IOPubChannel to support rendering images and such. With this request for programmatic access to Jupyter's std streams maybe all 4 (stdin/out/err and iopub) should be wrapped up into a nice little IO bundle that can be passed around and used by anything that needs it. This would result in an added API method on the BaseKernel like `getIO()` which is a reference to the bundle of streams that the BaseKernel will maintain. We can then include a constructor flag defaulting to `true` for whether the standard streams should be replaced. 

What do you think of something like a class `JupyterIO` with fields `out`, `err`, `in`, just like system and additionally `display`? 

The other question is should `out` and `err` be OutputStreams or PrintStreams like System? 

Also should these streams still no-op when there is no context for them to write, should they throw an exception, should they wait for context, should they default to the std streams, or something else?

**Comment by dgelessus** [comment]
> We can then include a constructor flag defaulting to `true` for whether the standard streams should be replaced.

Minor comment: IMHO it would be better to do this using a method - not because I want to change the flag after the kernel is instantiated, but because `super(false)` isn't very easy to understand (without looking at the docs).

> What do you think of something like a class `JupyterIO` with fields `out`, `err`, `in`, just like system and additionally `display`?

I'm honestly not all that familiar with Jupyter's architecture yet - does Jupyter provide stdout and stderr streams that are separate from `display` calls, or does Jupyter only have `display` and the basekernel redirects stdout and stderr into that?

In any case, exposing all of the streams seems like a good idea, since the stdin/out/err architecture is so common. Even if a kernel implementation doesn't need the streams, it can simply ignore them and only use `display`.

> The other question is should `out` and `err` be OutputStreams or PrintStreams like System?

I'd say `PrintStream` to mirror `System.out` and `System.err`, and to make them easier to use by hand. Also I think `PrintStream` is the usual type for "something like stdout", see for example [`Throwable.printStackTrace(PrintStream)`](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#printStackTrace-java.io.PrintStream-).

> Also should these streams still no-op when there is no context for them to write, should they throw an exception, should they wait for context, should they default to the std streams, or something else?

This is a difficult one 😃 This situation seems to me like it should never happen (you're only supposed to produce output if there's actually a place for the output to go) so the safest approach would be to throw an `IllegalStateException` if the streams are written to outside of an `eval` call. On the other hand, if user code spawns a background thread that writes to stdout after the main code has finished, it's probably better to ignore the extra output than to throw an exception.

Maybe the streams should be `close`d after `eval` finishes, and new ones created for the next `eval` call? That would be a bit more "normal" behavior than an `IllegalStateException` (although it probably doesn't make a huge difference, I doubt that most code would handle a closed stdout very gracefully...).

**Comment by SpencerPark** [comment]
>   Minor comment: IMHO it would be better to do this using a method - not because I want to change the flag after the kernel is instantiated, but because super(false) isn't very easy to understand (without looking at the docs).

Great point, I appreciate good API design tips. 

>   does Jupyter provide stdout and stderr streams that are separate from display calls, or does Jupyter only have display and the basekernel redirects stdout and stderr into that?

The _display_ stream is actually different than stdout/stderr so there are conceptually 3 out and the 1 in despite the 3 out displaying in the same place in the notebook.

>   I think PrintStream is the usual type for "something like stdout", see for example Throwable.printStackTrace(PrintStream).

Sounds good, also rationale is convincing. PrintStreams it is!

>    On the other hand, if user code spawns a background thread that writes to stdout after the main code has finished, it's probably better to ignore the extra output than to throw an exception.

A common thing is related to event handlers especially for things like widgets where you would write some debug messages that you never see because the execution finished. I believe the messages would end up on the stdout of the server which is why the current behavior regarding the streams is to redirect back to the original stdout after execution. Another option is to keep them open and send to the last executed cell's stdout.

>    I doubt that most code would handle a closed stdout very gracefully

I agree, not sure anyone ever assumes that stdout may be closed. (I certainly don't). I am leaning towards a solution that causes the least noise, whether that is silently failing or redirecting the stream data somewhere else I'm not quite sure. Maybe to get the best of both we can support a query for if the streams are directly connected or not in case kernels really need to know. If you are not too strong on an opinion I'll see what seems natural when I'm writing :).

Thank you for the comments, if you release your kernel on github or else where please let me know as I am very curious to see. Hopefully I can get to an implementation soon!

**Comment by dgelessus** [comment]
> Another option is to keep them open and send to the last executed cell's stdout.

Right, that's another possibility... I actually read about this today, while I was looking for something else in the Jupyter kernel docs, and came across [this warning](https://jupyter-client.readthedocs.io/en/latest/messaging.html#kernel-status):

> Asynchronous output (e.g. from background threads) may be produced after the kernel has sent the idle status message that signals the completion of the request. The handling of these out-of-order output messages is currently undefined in this specification, but the Jupyter Notebook continues to handle IOPub messages associated with a given request after the idle message has arrived, as long as the output area corresponding to that request is still active.

I think what the warning means is that if you send more output for a cell that has "officially" finished executing, Jupyter Notebook will add that output to the cell, but that behavior is not part of the specification. (As I said before, I'm not very familiar with the low-level details of Jupyter kernels, so I might be reading this wrong 😄) To me this sounds like "this is the current behavior, but it's not official and might change later", so it might be best not to rely on it.

I'd be fine with any of the possible solutions; in my kernel this specific situation can never occur (unless I mess something up in the implementation).

> if you release your kernel on github or else where please let me know as I am very curious to see

The kernel is in an internal repo at the moment, but I'll probably mirror or move it to a public repo in the future. I'll let you know once I do that.

> Hopefully I can get to an implementation soon!

Thank you very much for taking the time to implement this! 😃

**Comment by SpencerPark** [comment]
Alright the kernel has 2 additional methods `setShouldReplaceStdStreams(boolean)` and `getIO()`. The latter returns a `JupyterIO` bundle with fields that should feel just like `System`. If not _attached_ (which can be queries with `isAttached()` if necessary) then all of the operations are simply a no-op. 

This is published in `2.2.0-SNAPSHOT`.

**Comment by dgelessus** [comment]
:+1: Works perfectly. Thank you!

If you're interested, here's the repo for the kernel that I'm working on: https://gitlab.cs.uni-duesseldorf.de/dgelessus/prob2-jupyter-kernel

**Comment by SpencerPark** [comment]
> If you're interested, here's the repo for the kernel that I'm working on: https://gitlab.cs.uni-duesseldorf.de/dgelessus/prob2-jupyter-kernel

Very interested, thanks!
